### ISSUE TITLE
Prompting for visitor name

### ISSUE THREAD

**Issue by stephpetry** [AcroMace/receptionkit#1]
Hey! It would be awesome to be able to ask the visitor name before asking who he is looking for. This would show in slack as "visitor name is looking for employee name". This would enable us to have a necessary check in process which would complete the tool at least for our needs. 

Thanks!!

**Comment by AcroMace** [comment]
@stephpetry Done! The app should now ask for the visitor's name before asking who they are looking for. Thank you for the suggestion! :)

![screenshot 2015-06-15 18 12 56](https://cloud.githubusercontent.com/assets/4536299/8171956/1c915c4e-138a-11e5-852c-e1e0e171c127.png)

**Comment by stephpetry** [comment]
Thanks so much Andy!!
