### ISSUE TITLE
Readme instructions

### ISSUE THREAD

**Issue by ghost** [AcroMace/receptionkit#3]
The readme instructions aren't super clear for someone that has never built and installed an iOS app on to an iPad.

Could you perhaps provide a more in-depth (external is fine) guide on how to fully install this software?

> pod install
> Build and run the app

These 2 lines are where I'm unsure.

Thanks

**Comment by AcroMace** [comment]
Hey there, thanks for the feedback! The instructions have been updated. Could you confirm if it's clear enough now?

**Comment by ghost** [comment]
Much better, thank you.
