### ISSUE TITLE
Add sound support

### ISSUE THREAD

**Issue by dannytranlx** [AcroMace/receptionkit#33]
Hi @AcroMace, I hope all is well.

Turns out we're bad at answering the door at Smooch. What do you think about adding a bell or a ringtone when "assistance" is requested?

The idea would be to connect a little speaker to the iPad through Bluetooth or the audio jack on the other side of the wall, so it acts like a doorbell.

Or even without external speakers, it could use the built-in speakers to give a feedback to the visitor.

Maybe include some royalty free audio and let users customize their own sound if needed.

**Comment by AcroMace** [comment]
Sounds good! This should be pretty easy to add as well, I'll look into it right after I finish my finals! :)

**Comment by AcroMace** [comment]
The doorbell sound is now in master! :)

**Comment by dannytranlx** [comment]
We just pushed this build to our iPad, it works great, thanks Andy!
